/* Generated by AN DISI Unibo */ 
package it.unibo.manager

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Manager ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						forward("turnOn", "turnOn(1)" ,"led" ) 
						delay(500) 
						forward("turnOff", "turnOff(1)" ,"led" ) 
						delay(500) 
						forward("turnOn", "turnOn(1)" ,"led" ) 
						delay(500) 
						forward("turnOff", "turnOff(1)" ,"led" ) 
					}
				}	 
			}
		}
}
