/* Generated by AN DISI Unibo */ 
package it.unibo.ctxlogicbutton
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "sys_bls_logical_architecture.pl", "sysRules.pl"
	)
}

