/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSys0
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "local host", this, "sys0.pl", "sysRules.pl"
	)
}

