/* Generated by AN DISI Unibo */ 
package it.unibo.ctxbutton
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "sys_bls_problem_analysis.pl", "sysRules.pl"
	)
}

