/* Generated by AN DISI Unibo */ 
package it.unibo.button

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Button ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("BUTTON init done. Default initial led and button state: Off")
					}
					 transition( edgeName="goto",targetState="turningOff", cond=doswitch() )
				}	 
				state("turningOff") { //this:State
					action { //it:State
						request("cmdOff", "cmdOff(0)" ,"led" )  
					}
					 transition(edgeName="t00",targetState="off",cond=whenReply("ack"))
				}	 
				state("off") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	BUTTON turned OFF	")
					}
					 transition(edgeName="t01",targetState="turningOn",cond=whenEvent("button"))
				}	 
				state("turningOn") { //this:State
					action { //it:State
						request("cmdOn", "cmdOn(1)" ,"led" )  
					}
					 transition(edgeName="t02",targetState="on",cond=whenReply("ack"))
				}	 
				state("on") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	BUTTON turned ON	")
					}
					 transition(edgeName="t03",targetState="turningOff",cond=whenEvent("button"))
				}	 
			}
		}
}
